[default]
TELEGRAM_API_ID = "Veja qual em my.telegram.org"
MONGO_CONNECTION_STRING = "Link de conexão ao seu banco de dados Mongo"
TELEGRAM_API_HASH = "Veja qual em my.telegram.org"

[development]
MONGO_DATABASE_NAME = "Nome do banco de dados do seu bot rodando no desenvolvimento"
TELEGRAM_APP_NAME = "Nome do arquivo de sessão do seu bot, pode apontar para /tmp/bot"
TELEGRAM_BOT_TOKEN = "Token do seu bot rodando no desenvolvimento"

[production]
MONGO_DATABASE_NAME = "Nome do banco de dados do seu bot rodando na produção"
TELEGRAM_APP_NAME = "Nome do arquivo de sessão do seu bot, pode apontar para /tmp/bot"
TELEGRAM_BOT_TOKEN = "Token do seu bot rodando na produção"

# Ao final, mova este arquivo para .secrets.toml e (opcionalmente) remova esta linha